version: "3.8"
services:
  worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN # defaults to None
      API_ID: $API_ID # defaults to None
      API_HASH: $API_HASH # defaults to None
      PREFIX_HANDLER: $PREFIX_HANDLER # defult to ! and /
      MESSAGE_DUMP:
      DB_URI: 
      OKTETO_TOKEN: $OKTETO_TOKEN
